/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Exercises {
  created_at: Generated<Timestamp>;
  description: string | null;
  example_url: string | null;
  id: Generated<number>;
  name: string;
  training_id: number;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface ExerciseTypes {
  value: string;
}

export interface Repetitions {
  break_actual_duration: Timestamp | null;
  break_expected_duration: Timestamp | null;
  count: number;
  created_at: Generated<Timestamp>;
  end_date: Timestamp | null;
  exercises_id: number;
  finish_type: string;
  id: Generated<number>;
  start_date: Timestamp | null;
  target_count: number | null;
  target_weight: Numeric | null;
  updated_at: Generated<Timestamp>;
  weight: Numeric;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  ip: string | null;
  revoked: Generated<boolean>;
  token: string;
  user_agent: string | null;
  users_id: number;
  uuid: string;
}

export interface Trainings {
  created_at: Generated<Timestamp>;
  description: string | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  name: string;
  post_training_duration: Timestamp | null;
  start_date: Timestamp | null;
  updated_at: Generated<Timestamp>;
  worm_up_duration: Timestamp | null;
}

export interface Users {
  avatar: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  password_hash: string;
  screen_name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  exercise_types: ExerciseTypes;
  exercises: Exercises;
  repetitions: Repetitions;
  sessions: Sessions;
  trainings: Trainings;
  users: Users;
}
