include:
  - local: ci/install-environment.yml

image: node:24.18.1
stages:
  - monorepo
  - docker-build
  - deploy-dev-stage
  - deploy-production

# ======================== CHUNKS ===============================
.ssh-prepare: &ssh-prepare
  - apk add --no-cache openssh-client gettext bash
  - eval "$(ssh-agent -s)"
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $SSH_KNOWN_HOSTS > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - ssh-add ~/.ssh/id_rsa

# ======================== TEMPLATES ===============================
.client-deploy-template:
  image: alpine:3.20
  tags: [registry, dind]
  before_script:
    - *ssh-prepare

  script:
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "rm -f ${REMOTE_DIR}/docker-compose.yml"
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "touch ${REMOTE_DIR}/docker-compose.yml"
    - scp docker-compose.yml "${DEPLOY_USER}@${DEPLOY_HOST}:${REMOTE_DIR}/docker-compose.yml"
    - |
      ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "
        set -euo pipefail
        cd ${REMOTE_DIR}
        echo '${CI_REGISTRY_PASSWORD}' | docker login '${CI_REGISTRY}' -u '${CI_REGISTRY_USER}' --password-stdin
        docker compose -f docker-compose.yml pull
        docker compose -f docker-compose.yml up -d
        docker system prune -a -f
      "

.client-build-template:
  image: docker:27.4.1-cli
  needs:
    - job: lint
      optional: false
    - job: test
      optional: false

  variables:
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_TLS_CERTDIR: ''

  services:
    - name: docker:27.4.1-dind
      alias: docker
      command: ['--tls=false']
  tags: [registry, dind]

  before_script:
    - apk add --no-cache git git-lfs
    - git lfs install
    - git lfs pull

  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - IMAGE_REF="${CI_REGISTRY_IMAGE}:${CLIENT_NAME}-sha-${CI_COMMIT_SHORT_SHA}"
    - |
      docker build \
        -f ./clients/tracker-client/Dockerfile \
        --build-arg VITE_API_BASE_URL="$BASE_URL" \
        --build-arg HUSKY="0" \
        -t "$IMAGE_REF" \
        .

    - docker push "$IMAGE_REF"

.app-build-template:
  image: docker:27.4.1-cli
  needs:
    - job: lint
      optional: false
    - job: test
      optional: false
  services:
    - name: docker:27.4.1-dind
      alias: docker
      command: ['--tls=false']
  tags: [registry, dind]
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_TLS_CERTDIR: ''

  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

    - IMAGE_REF="${CI_REGISTRY_IMAGE}:${APP_NAME}-sha-${CI_COMMIT_SHORT_SHA}"

    - |
      docker build \
        -f ./apps/${APP_NAME}/Dockerfile \
        -t "$IMAGE_REF" \
        .

    - docker push "$IMAGE_REF"

.app-deploy-template:
  image: alpine:3.20
  tags: [registry, dind]
  before_script:
    - *ssh-prepare
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "mkdir -p ${REMOTE_DIR}"

  script:
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "rm -f ${REMOTE_DIR}/docker-compose.yml"
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "rm -f ${REMOTE_DIR}/.env"
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "touch ${REMOTE_DIR}/docker-compose.yml"
    - scp docker-compose.yml "${DEPLOY_USER}@${DEPLOY_HOST}:${REMOTE_DIR}/docker-compose.yml"
    - scp "$ENV" "${DEPLOY_USER}@${DEPLOY_HOST}:${REMOTE_DIR}/.env"
    - |
      ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "
        set -euo pipefail
        cd ${REMOTE_DIR}
        echo '${CI_REGISTRY_PASSWORD}' | docker login '${CI_REGISTRY}' -u '${CI_REGISTRY_USER}' --password-stdin
        docker compose -f docker-compose.yml pull
        docker compose -f docker-compose.yml up -d
        docker system prune -a -f
      "

lint:
  interruptible: true
  stage: monorepo
  tags: [docker]
  extends: .install_environment
  variables:
    GIT_STRATEGY: clone
  script:
    - pnpm run format:all --concurrency=1
    - pnpm run lint:all --concurrency=1

test:
  interruptible: true
  stage: monorepo
  tags: [docker]
  extends: .install_environment
  variables:
    GIT_STRATEGY: clone
  script:
    - pnpm run test:all --concurrency=1

# ======================== BUILD ===============================

#tracker-client:build:
#  stage: docker-build
#  when: manual
#  extends: .client-build-template
#  variables:
#    BASE_URL: '$TRACKER_CLIENT_API_URL'
#    CLIENT_NAME: 'tracker-client'

api-gateway:build:
  stage: docker-build
  when: manual
  extends: .app-build-template
  variables:
    APP_NAME: 'api-gateway'

auth-service:build:
  stage: docker-build
  when: manual
  extends: .app-build-template
  variables:
    APP_NAME: 'auth-service'

goal-service:build:
  stage: docker-build
  when: manual
  extends: .app-build-template
  variables:
    APP_NAME: 'goal-service'

training-service:build:
  stage: docker-build
  when: manual
  extends: .app-build-template
  variables:
    APP_NAME: 'training-service'

# ======================== DEPLOY DEV ===============================

#tracker-client:deploy:dev:
#  stage: deploy-dev-stage
#  when: manual
#  dependencies:
#    - tracker-client:build
#  needs:
#    - job: tracker-client:build
#      optional: false
#  extends: .client-deploy-template
#  before_script:
#    - !reference [.client-deploy-template, before_script]
#    - envsubst < sources/docker-compose.clients-temp.yml > docker-compose.yml
#
#  variables:
#    DEPLOY_HOST: '$DEV_STAGE_HOST'
#    DEPLOY_USER: '$DEV_STAGE_DEPLOY_USER'
#    REMOTE_DIR: '$DEV_STAGE_REMOTE_CLIENT_DIR'

api-gateway:deploy:dev:
  stage: deploy-dev-stage
  when: manual
  extends: .app-deploy-template
  needs:
    - job: api-gateway:build
      optional: false

  before_script:
    - !reference [.app-deploy-template, before_script]
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "rm -f ${REMOTE_DIR}/public.pem"
    - scp "$AUTH_PUBLIC_KEY_DEV" "${DEPLOY_USER}@${DEPLOY_HOST}:${REMOTE_DIR}/public.pem"
    - envsubst '${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHORT_SHA}' < sources/docker-compose.api-gateway.yml > docker-compose.yml

  variables:
    ENV: '$API_GATEWAY_ENV'
    DEPLOY_HOST: '$DEV_STAGE_HOST'
    DEPLOY_USER: '$DEV_STAGE_DEPLOY_USER'
    REMOTE_DIR: '$DEV_STAGE_REMOTE_APP_DIR/api-gateway'

auth-service:deploy:dev:
  stage: deploy-dev-stage
  when: manual
  extends: .app-deploy-template
  needs:
    - job: auth-service:build
      optional: false

  before_script:
    - !reference [.app-deploy-template, before_script]
    - ssh "${DEPLOY_USER}@${DEPLOY_HOST}" "rm -f ${REMOTE_DIR}/private.pem"
    - scp "$AUTH_PRIVATE_KEY_DEV" "${DEPLOY_USER}@${DEPLOY_HOST}:${REMOTE_DIR}/private.pem"
    - envsubst '${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHORT_SHA}' < sources/docker-compose.auth-service.yml > docker-compose.yml

  variables:
    ENV: '$AUTH_SERVICE_ENV'
    DEPLOY_HOST: '$DEV_STAGE_HOST'
    DEPLOY_USER: '$DEV_STAGE_DEPLOY_USER'
    REMOTE_DIR: '$DEV_STAGE_REMOTE_APP_DIR/auth-service'

goal-service:deploy:dev:
  stage: deploy-dev-stage
  when: manual
  extends: .app-deploy-template
  needs:
    - job: goal-service:build
      optional: false

  before_script:
    - !reference [.app-deploy-template, before_script]
    - envsubst '${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHORT_SHA}' < sources/docker-compose.goal-service.yml > docker-compose.yml

  variables:
    ENV: '$GOAL_SERVICE_ENV'
    DEPLOY_HOST: '$DEV_STAGE_HOST'
    DEPLOY_USER: '$DEV_STAGE_DEPLOY_USER'
    REMOTE_DIR: '$DEV_STAGE_REMOTE_APP_DIR/goal-service'

training-service:deploy:dev:
  stage: deploy-dev-stage
  when: manual
  extends: .app-deploy-template
  needs:
    - job: training-service:build
      optional: false

  before_script:
    - !reference [.app-deploy-template, before_script]
    - envsubst '${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHORT_SHA}' < sources/docker-compose.training-service.yml > docker-compose.yml

  variables:
    ENV: '$TRAINING_SERVICE_ENV'
    DEPLOY_HOST: '$DEV_STAGE_HOST'
    DEPLOY_USER: '$DEV_STAGE_DEPLOY_USER'
    REMOTE_DIR: '$DEV_STAGE_REMOTE_APP_DIR/training-service'

# ======================== DEPLOY PROD ===============================
#tracker-client:deploy:prod:
#  stage: deploy-production
#  when: manual
#  dependencies:
#    - tracker-client:build
#  needs:
#    - job: tracker-client:build
#      optional: false
#  extends: .client-deploy-template
#  before_script:
#    - !reference [.client-deploy-template, before_script]
#    - envsubst < sources/docker-compose.clients-temp.yml > docker-compose.yml
#
#  variables:
#    DEPLOY_HOST: '$PRODUCTION_HOST'
#    DEPLOY_USER: '$PROD_DEPLOY_USER'
#    REMOTE_DIR: '$PROD_REMOTE_CLIENT_DIR'

api-gateway:deploy:prod:
  stage: deploy-production
  when: manual
  extends: .app-deploy-template
  needs:
    - job: api-gateway:build
      optional: false

  before_script:
    - !reference [.app-deploy-template, before_script]
    - envsubst '${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHORT_SHA}' < sources/docker-compose.api-gateway.yml > docker-compose.yml

  variables:
    ENV: '$API_GATEWAY_PROD_ENV'
    DEPLOY_HOST: '$PRODUCTION_HOST'
    DEPLOY_USER: '$PROD_DEPLOY_USER'
    REMOTE_DIR: '$PROD_REMOTE_APP_DIR/api-gateway'

goal-service:deploy:prod:
  stage: deploy-production
  when: manual
  extends: .app-deploy-template
  needs:
    - job: goal-service:build
      optional: false

  before_script:
    - !reference [.app-deploy-template, before_script]
    - envsubst '${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHORT_SHA}' < sources/docker-compose.goal-service.yml > docker-compose.yml

  variables:
    ENV: '$GOAL_SERVICE_PROD_ENV'
    DEPLOY_HOST: '$PRODUCTION_HOST'
    DEPLOY_USER: '$PROD_DEPLOY_USER'
    REMOTE_DIR: '$PROD_REMOTE_APP_DIR/goal-service'

training-service:deploy:prod:
  stage: deploy-production
  when: manual
  extends: .app-deploy-template
  needs:
    - job: training-service:build
      optional: false

  before_script:
    - !reference [.app-deploy-template, before_script]
    - envsubst '${CI_REGISTRY_IMAGE} ${CI_COMMIT_SHORT_SHA}' < sources/docker-compose.training-service.yml > docker-compose.yml

  variables:
    ENV: '$TRAINING_SERVICE_PROD_ENV'
    DEPLOY_HOST: '$PRODUCTION_HOST'
    DEPLOY_USER: '$PROD_DEPLOY_USER'
    REMOTE_DIR: '$PROD_REMOTE_APP_DIR/training-service'
