packages:
  - "apps/*"
  - "libs/*"
  - "configs/**"

catalog:
  "zod": "3.24.4"
  "nestjs-zod": "^4.3.1"
  "typescript": "~5.8.3"
  "typescript-eslint": "^8.30.1"
  "@types/node": "^22.15.17"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "@typescript-eslint/eslint-plugin": "^8.24.1"
  "eslint-config-prettier": "^10.1.5"
  "eslint-plugin-prettier": "^5.4.0"
  "ts-patch": "^3.3.0"
  "eslint": "9.25.0"
  "@eslint/js": "^9.25.0"
  "prettier": "^3.5.3"
  "qs": "6.14.0"
  "@types/qs": "^6.9.18"
