import {
  GetGroupUserInboxHandler,
  GetInboxByUserIdQuery,
  GetDetailedGroupsHandler,
  GetDetailedGroupsQuery,
  GetTasksQuery,
  GetTasksHandler,
  GetAssignableTasksQuery,
  GetAssignableTasksHandler,
  GetUserGroupsQuery,
  GetUserGroupsHandler,
  GetAssignableGroupsQuery,
  GetAssignableGroupsHandler,
} from './queries';
import {
  GroupCheckerService,
  GroupsService,
  InboxGroupCheckerService,
  TaskCheckerService,
  TaskQueryService,
  TaskService,
  GoalPublicService,
} from './services';
import { Module } from '@nestjs/common';
import { TasksInfrastructureModule } from '../infrastructure/tasks-infrastructure.module';
import {
  CreateTaskCommand,
  CreateTaskUseCase,
  CreateTaskHandler,
  CreateTaskInInboxUseCase,
  CreateTaskInInboxHandler,
  CreateTaskInInboxCommand,
  CreateInboxGroupCommand,
  CreateInboxGroupHandler,
  CreateInboxGroupUseCase,
  UpdateInboxTaskCommand,
  UpdateInboxTaskHandler,
  UpdateInboxTaskUseCase,
  ReplaceTaskCommand,
  ReplaceTaskHandler,
  ReplaceTaskUseCase,
  SoftDeleteTaskCommand,
  SoftDeleteTaskHandler,
  SoftDeleteTaskUseCase,
  CloneTaskCommand,
  CloneTaskHandler,
  CloneTaskUseCase,
  AssignTaskToGroupCommand,
  AssignTaskToGroupHandler,
  AssignTaskToGroupUseCase,
  AssignTaskToInboxCommand,
  AssignTaskToInboxHandler,
  AssignTaskToInboxUseCase,
  UnassignTaskFromGroupCommand,
  UnassignTaskFromGroupHandler,
  UnassignTaskFromGroupUseCase,
  CreateGroupCommand,
  CreateGroupHandler,
  CreateGroupUseCase,
  ReplaceGroupCommand,
  ReplaceGroupHandler,
  ReplaceGroupUseCase,
  DeleteGroupCommand,
  DeleteGroupHandler,
  DeleteGroupUseCase,
  FinishTaskCommand,
  FinishTaskHandler,
  FinishTaskUseCase,
  CompleteDeleteTaskCommand,
  CompleteDeleteTaskHandler,
  CompleteDeleteTaskUseCase,
  TaskRecoveryCommand,
  TaskRecoveryHandler,
  TaskRecoveryUseCase,
} from './use-cases';

const queries = [
  GetInboxByUserIdQuery,
  GetDetailedGroupsQuery,
  GetTasksQuery,
  GetAssignableTasksQuery,
  GetUserGroupsQuery,
  GetAssignableGroupsQuery,
];
const commands = [
  CreateTaskCommand,
  CreateTaskInInboxCommand,
  CreateInboxGroupCommand,
  UpdateInboxTaskCommand,
  ReplaceTaskCommand,
  SoftDeleteTaskCommand,
  CloneTaskCommand,
  AssignTaskToGroupCommand,
  AssignTaskToInboxCommand,
  UnassignTaskFromGroupCommand,
  ReplaceGroupCommand,
  CreateGroupCommand,
  DeleteGroupCommand,
  FinishTaskCommand,
  CompleteDeleteTaskCommand,
  TaskRecoveryCommand,
];
const handlers = [
  CreateTaskHandler,
  CreateTaskInInboxHandler,
  CreateInboxGroupHandler,
  GetGroupUserInboxHandler,
  UpdateInboxTaskHandler,
  ReplaceTaskHandler,
  SoftDeleteTaskHandler,
  CloneTaskHandler,
  AssignTaskToGroupHandler,
  AssignTaskToInboxHandler,
  UnassignTaskFromGroupHandler,
  ReplaceGroupHandler,
  CreateGroupHandler,
  DeleteGroupHandler,
  GetDetailedGroupsHandler,
  GetTasksHandler,
  GetAssignableTasksHandler,
  FinishTaskHandler,
  CompleteDeleteTaskHandler,
  TaskRecoveryHandler,
  GetUserGroupsHandler,
  GetAssignableGroupsHandler,
];
const useCases = [
  CreateTaskUseCase,
  CreateTaskInInboxUseCase,
  CreateInboxGroupUseCase,
  UpdateInboxTaskUseCase,
  ReplaceTaskUseCase,
  SoftDeleteTaskUseCase,
  CloneTaskUseCase,
  AssignTaskToGroupUseCase,
  AssignTaskToInboxUseCase,
  UnassignTaskFromGroupUseCase,
  ReplaceGroupUseCase,
  CreateGroupUseCase,
  DeleteGroupUseCase,
  FinishTaskUseCase,
  CompleteDeleteTaskUseCase,
  TaskRecoveryUseCase,
];

@Module({
  imports: [TasksInfrastructureModule],
  providers: [
    TaskService,
    GroupsService,
    TaskCheckerService,
    GroupCheckerService,
    InboxGroupCheckerService,
    TaskQueryService,
    GoalPublicService,
    ...commands,
    ...queries,
    ...handlers,
    ...useCases,
  ],
})
export class TasksApplicationModule {}
