import {
  GetGroupUserInboxHandler,
  GetInboxByUserIdQuery,
  GetUserGroupsHandler,
  GetUserGroupsQuery,
  GetDiaryTasksQuery,
  GetDiaryTasksHandler,
  GetAssignableTasksToGroupQuery,
  GetAssignableTasksToGroupHandler,
} from './queries';
import {
  GroupCheckerService,
  GroupsService,
  InboxGroupCheckerService,
  TaskCheckerService,
  TaskGroupCheckerService,
  TaskQueryService,
  TaskService,
} from '@/modules/tasks/application/services';
import { Module } from '@nestjs/common';
import { TasksInfrastructureModule } from '@/modules/tasks/infrastructure/tasks-infrastructure.module';
import {
  CreateTaskCommand,
  CreateTaskUseCase,
  CreateTaskHandler,
  CreateTaskInInboxUseCase,
  CreateTaskInInboxHandler,
  CreateTaskInInboxCommand,
  CreateInboxGroupCommand,
  CreateInboxGroupHandler,
  CreateInboxGroupUseCase,
  UpdateInboxTaskCommand,
  UpdateInboxTaskHandler,
  UpdateInboxTaskUseCase,
  ReplaceTaskCommand,
  ReplaceTaskHandler,
  ReplaceTaskUseCase,
  SoftDeleteTaskCommand,
  SoftDeleteTaskHandler,
  SoftDeleteTaskUseCase,
  CloneTaskCommand,
  CloneTaskHandler,
  CloneTaskUseCase,
  AssignTaskToGroupCommand,
  AssignTaskToGroupHandler,
  AssignTaskToGroupUseCase,
  AssignTaskToInboxCommand,
  AssignTaskToInboxHandler,
  AssignTaskToInboxUseCase,
  UnassignTaskFromGroupCommand,
  UnassignTaskFromGroupHandler,
  UnassignTaskFromGroupUseCase,
  CreateGroupCommand,
  CreateGroupHandler,
  CreateGroupUseCase,
  ReplaceGroupCommand,
  ReplaceGroupHandler,
  ReplaceGroupUseCase,
  DeleteGroupCommand,
  DeleteGroupHandler,
  DeleteGroupUseCase,
} from './use-cases';

const queries = [
  GetInboxByUserIdQuery,
  GetUserGroupsQuery,
  GetDiaryTasksQuery,
  GetAssignableTasksToGroupQuery,
];
const commands = [
  CreateTaskCommand,
  CreateTaskInInboxCommand,
  CreateInboxGroupCommand,
  UpdateInboxTaskCommand,
  ReplaceTaskCommand,
  SoftDeleteTaskCommand,
  CloneTaskCommand,
  AssignTaskToGroupCommand,
  AssignTaskToInboxCommand,
  UnassignTaskFromGroupCommand,
  ReplaceGroupCommand,
  CreateGroupCommand,
  DeleteGroupCommand,
];
const handlers = [
  CreateTaskHandler,
  CreateTaskInInboxHandler,
  CreateInboxGroupHandler,
  GetGroupUserInboxHandler,
  UpdateInboxTaskHandler,
  ReplaceTaskHandler,
  SoftDeleteTaskHandler,
  CloneTaskHandler,
  AssignTaskToGroupHandler,
  AssignTaskToInboxHandler,
  UnassignTaskFromGroupHandler,
  ReplaceGroupHandler,
  CreateGroupHandler,
  DeleteGroupHandler,
  GetUserGroupsHandler,
  GetDiaryTasksHandler,
  GetAssignableTasksToGroupHandler,
];
const useCases = [
  CreateTaskUseCase,
  CreateTaskInInboxUseCase,
  CreateInboxGroupUseCase,
  UpdateInboxTaskUseCase,
  ReplaceTaskUseCase,
  SoftDeleteTaskUseCase,
  CloneTaskUseCase,
  AssignTaskToGroupUseCase,
  AssignTaskToInboxUseCase,
  UnassignTaskFromGroupUseCase,
  ReplaceGroupUseCase,
  CreateGroupUseCase,
  DeleteGroupUseCase,
];

@Module({
  imports: [TasksInfrastructureModule],
  providers: [
    TaskService,
    GroupsService,
    TaskCheckerService,
    GroupCheckerService,
    TaskGroupCheckerService,
    InboxGroupCheckerService,
    TaskQueryService,
    ...commands,
    ...queries,
    ...handlers,
    ...useCases,
  ],
})
export class TasksApplicationModule {}
