/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Goals {
  cancel_reason: string | null;
  created_at: Timestamp;
  description: string | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  name: string;
  progress: Generated<number>;
  start_date: Timestamp;
  status_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface GoalStatuses {
  id: Generated<number>;
  name: string;
}

export interface GoalsToStages {
  goal_id: number;
  position: Generated<number>;
  stage_id: number;
}

export interface GoalToGoals {
  goal_id: number;
  master_goal_id: number;
  position: Generated<number>;
}

export interface Groups {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  progress: Generated<number>;
  status_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface GroupSettings {
  event_color: string;
  event_color_dark: string;
  event_selected_color: string;
  event_selected_color_dark: string;
  group_id: number;
  id: Generated<number>;
  is_default: Generated<boolean>;
  is_readonly: Generated<boolean>;
  is_visible: Generated<boolean>;
  line_color: string;
  line_color_dark: string;
  text_color: string;
  text_color_dark: string;
}

export interface GroupStatuses {
  id: Generated<number>;
  name: string;
}

export interface GroupToGoals {
  goal_id: number;
  group_id: number;
  position: Generated<number>;
}

export interface RecurrencesFrequencies {
  id: Generated<number>;
  name: string;
}

export interface RecurrenceStatuses {
  id: Generated<number>;
  name: string;
}

export interface Stages {
  created_at: Generated<Timestamp>;
  description: string | null;
  end_date: Timestamp;
  id: Generated<number>;
  settings_id: number | null;
  start_date: Timestamp;
  status_id: number;
  type_id: number;
  updated_at: Generated<Timestamp>;
}

export interface StageStatuses {
  id: Generated<number>;
  name: string;
}

export interface StageTypes {
  id: Generated<number>;
  name: string;
}

export interface Tags {
  id: Generated<number>;
  name: string;
}

export interface TagToTasks {
  tag_id: number;
  task_id: number;
}

export interface Tasks {
  cancel_reason: string | null;
  created_at: Generated<Timestamp>;
  deadline: Timestamp | null;
  description: string | null;
  end_date: Timestamp | null;
  group_id: number | null;
  id: Generated<number>;
  name: string;
  priority: Generated<number>;
  start_date: Timestamp | null;
  status_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface TaskSettings {
  icon: string | null;
  id: Generated<number>;
  is_all_day: Generated<boolean>;
  task_id: number;
}

export interface TaskRecurrenceOverrideSettings {
  icon: string | null;
  id: Generated<number>;
  is_all_day: Generated<boolean>;
  tasks_recurrences_overrides_id: number;
}

export interface TasksRecurrences {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  interval: number | null;
  monthdays: number[] | null;
  pattern: string;
  recurrence_frequencies_id: number;
  recurrence_status_id: number;
  start_date: Timestamp;
  task_id: number;
  timezone: string;
  until_date: Timestamp | null;
  updated_at: Generated<Timestamp>;
  user_id: number;
  weekdays: number[] | null;
  weekstart: number;
  yearmonths: number[] | null;
}

export interface TasksRecurrencesOverrides {
  cancel_reason: string | null;
  created_at: Generated<Timestamp>;
  deadline: Timestamp | null;
  description: string | null;
  end_date: Timestamp | null;
  group_id: number | null;
  id: Generated<number>;
  name: string;
  override_type_id: number;
  priority: Generated<number>;
  recurrence_id: number;
  recurrence_start: Timestamp;
  start_date: Timestamp;
  status_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface TasksRecurrencesOverrideTypes {
  id: Generated<number>;
  name: string;
}

export interface TaskStatuses {
  id: Generated<number>;
  name: string;
}

export interface TaskToGroup {
  group_id: number;
  position: Generated<number>;
  task_id: number;
}

export interface DB {
  goal_statuses: GoalStatuses;
  goal_to_goals: GoalToGoals;
  goals: Goals;
  goals_to_stages: GoalsToStages;
  group_statuses: GroupStatuses;
  group_settings: GroupSettings;
  group_to_goals: GroupToGoals;
  groups: Groups;
  recurrence_statuses: RecurrenceStatuses;
  recurrences_frequencies: RecurrencesFrequencies;
  stage_statuses: StageStatuses;
  stage_types: StageTypes;
  stages: Stages;
  tag_to_tasks: TagToTasks;
  tags: Tags;
  task_statuses: TaskStatuses;
  task_recurrence_override_settings: TaskRecurrenceOverrideSettings;
  task_settings: TaskSettings;
  task_to_group: TaskToGroup;
  tasks: Tasks;
  tasks_recurrences: TasksRecurrences;
  tasks_recurrences_override_types: TasksRecurrencesOverrideTypes;
  tasks_recurrences_overrides: TasksRecurrencesOverrides;
}
