/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Goals {
  cancel_reason: string | null;
  created_at: Timestamp;
  description: string | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  name: string;
  progress: Generated<number>;
  start_date: Timestamp;
  status_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface GoalStatuses {
  id: Generated<number>;
  name: string;
}

export interface GoalsToStages {
  goal_id: number;
  position: Generated<number>;
  stage_id: number;
}

export interface GoalToGoals {
  goal_id: number;
  master_goal_id: number;
  position: Generated<number>;
}

export interface Groups {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  progress: Generated<number>;
  progress_result: number;
  status_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
}

export interface GroupStatuses {
  id: Generated<number>;
  name: string;
}

export interface GroupToGoals {
  goal_id: number;
  group_id: number;
  position: Generated<number>;
}

export interface Stages {
  created_at: Generated<Timestamp>;
  description: string | null;
  end_date: Timestamp;
  id: Generated<number>;
  settings_id: number | null;
  start_date: Timestamp;
  status_id: number;
  type_id: number;
  updated_at: Generated<Timestamp>;
}

export interface StageStatuses {
  id: Generated<number>;
  name: string;
}

export interface StageTypes {
  id: Generated<number>;
  name: string;
}

export interface Tags {
  id: Generated<number>;
  name: string;
}

export interface TagToTasks {
  tag_id: number;
  task_id: number;
}

export interface Tasks {
  cancel_reason: string | null;
  created_at: Generated<Timestamp>;
  deadline: Timestamp | null;
  description: string | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  name: string;
  priority: Generated<number>;
  recurrence: string | null;
  start_date: Timestamp | null;
  status_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
  weight: Generated<number>;
}

export interface TasksRecurrenceOverrides {
  cancel_reason: string | null;
  created_at: Generated<Timestamp>;
  deadline: Timestamp | null;
  description: string | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  name: string;
  override_type_id: number;
  priority: Generated<number>;
  start_date: Timestamp;
  status_id: number;
  task_id: number;
  updated_at: Generated<Timestamp>;
  user_id: number;
  weight: Generated<number>;
}

export interface TasksRecurrenceOverrideTypes {
  id: Generated<number>;
  name: string;
}

export interface TaskStatuses {
  id: Generated<number>;
  name: string;
}

export interface TaskToGroup {
  group_id: number;
  position: Generated<number>;
  task_id: number;
}

export interface DB {
  goal_statuses: GoalStatuses;
  goal_to_goals: GoalToGoals;
  goals: Goals;
  goals_to_stages: GoalsToStages;
  group_statuses: GroupStatuses;
  group_to_goals: GroupToGoals;
  groups: Groups;
  stage_statuses: StageStatuses;
  stage_types: StageTypes;
  stages: Stages;
  tag_to_tasks: TagToTasks;
  tags: Tags;
  task_statuses: TaskStatuses;
  task_to_group: TaskToGroup;
  tasks: Tasks;
  tasks_recurrence_override_types: TasksRecurrenceOverrideTypes;
  tasks_recurrence_overrides: TasksRecurrenceOverrides;
}
