const TasksToken = {
  WRITE_REPOSITORY: Symbol.for('TASKS_WRITE_REPOSITORY'),
  READ_REPOSITORY: Symbol.for('TASKS_READ_REPOSITORY'),
};

const GroupsToken = {
  WRITE_REPOSITORY: Symbol.for('GROUPS_WRITE_REPOSITORY'),
  READ_REPOSITORY: Symbol.for('GROUPS_READ_REPOSITORY'),

  INBOX_WRITE_REPOSITORY: Symbol.for('INBOX_WRITE_REPOSITORY'),
  INBOX_READ_REPOSITORY: Symbol.for('INBOX_READ_REPOSITORY'),
};

export { TasksToken, GroupsToken };
