const TasksToken = {
  WRITE_REPOSITORY: Symbol('TASKS_WRITE_REPOSITORY'),
  READ_REPOSITORY: Symbol('TASKS_READ_REPOSITORY'),
};

const GroupsToken = {
  WRITE_REPOSITORY: Symbol('GROUPS_WRITE_REPOSITORY'),
  READ_REPOSITORY: Symbol('GROUPS_READ_REPOSITORY'),

  INBOX_WRITE_REPOSITORY: Symbol('INBOX_WRITE_REPOSITORY'),
  INBOX_READ_REPOSITORY: Symbol('INBOX_READ_REPOSITORY'),
};

export { TasksToken, GroupsToken };
