/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение общих данных о вошедшем в систему пользователе */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация пользователя
         * @description Возвращает access-token в теле и устанавливает refresh-token в cookie (HttpOnly) strict
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновление токена пользователя
         * @description Возвращает access-token в теле и устанавливает refresh-token в cookie (HttpOnly)
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход пользователя из системы */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход пользователя в систему */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/referral-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Генерация реферального токена */
        post: operations["AuthController_generateReferralToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/referral-token/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Валидация реферального токена */
        get: operations["AuthController_validateReferralToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение активной тренировки на текущий день */
        get: operations["TrainingsController_getActiveTraining"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение тренировок */
        get: operations["TrainingsController_getTrainings"];
        put?: never;
        /** Создание тренировки */
        post: operations["TrainingsController_createTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{trainingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение одной тренировки с упражнениями */
        get: operations["TrainingsController_getOneTrainingsWithExercises"];
        /**
         * Обновление тренировки с упражнениями
         * @description nullable поля очищают значения
         */
        put: operations["TrainingsController_putTraining"];
        post?: never;
        /** Удаление тренировки */
        delete: operations["TrainingsController_deleteTraining"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создание тренировки по шаблону */
        post: operations["TrainingsController_createTrainingByTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Назначение тренировки на дату */
        post: operations["TrainingsController_assignTrainings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{trainingId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Начать тренировку */
        post: operations["TrainingsController_stratTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{trainingId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить тренировку */
        post: operations["TrainingsController_finishTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{trainingId}/repetition/{repetitionId}/fact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Установить факт */
        post: operations["TrainingsController_setFact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings/{trainingId}/repetition/{repetitionId}/break": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Установить факт отдыха в повторении */
        post: operations["TrainingsController_setBrakFact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение шаблонов тренировок */
        get: operations["TrainingTemplatesController_getTrainingTemplates"];
        put?: never;
        /** Создание шаблона тренировки */
        post: operations["TrainingTemplatesController_createTraining"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trainings-templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение одного шаблона тренировки с упражнениями */
        get: operations["TrainingTemplatesController_getOneTrainingsWithExercises"];
        /**
         * Обновление шаблона тренировки с упражнениями
         * @description nullable поля очищают значения
         */
        put: operations["TrainingTemplatesController_putTraining"];
        post?: never;
        /** Удаление тренировки */
        delete: operations["TrainingTemplatesController_deleteTraining"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение шаблонов упражнений */
        get: operations["ExercisesController_getExercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exerciseId}/repetitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение одного упражнения с повторениями */
        get: operations["ExercisesController_getOneExerciseWithRepetitions"];
        /**
         * Обновление упражнения с повторениями
         * @description nullable поля очищают значения
         */
        put: operations["ExercisesController_updateExerciseWithRepetitions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/repetitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создание упражнения c повторениями */
        post: operations["ExercisesController_createExerciseWithRepetitions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exerciseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удаление упражнения */
        delete: operations["ExercisesController_deleteExerciseTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение группы IN BOX с делами */
        get: operations["GroupsController_getInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение групп с делами */
        get: operations["GroupsController_getUserGroups"];
        put?: never;
        /** Создание группы */
        post: operations["GroupsController_createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{groupId}/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение групп с подробностями */
        get: operations["GroupsController_getDetailedGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/assignable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Группы доступные к назначению дел */
        get: operations["GroupsController_getAssignableGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Редактирование группы */
        put: operations["GroupsController_replaceGroup"];
        post?: never;
        /** Удаление группы */
        delete: operations["GroupsController_deleteGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение дел */
        get: operations["TasksController_getTasks"];
        put?: never;
        /** Создание дела */
        post: operations["TasksController_createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/diary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение дел для ежедневника */
        get: operations["TasksController_getDiaryTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/deleted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение удаленных дел */
        get: operations["TasksController_getDeletedTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/archived": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение архивные дел */
        get: operations["TasksController_getArchivedTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/assignable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получение дел доступных к группировке */
        get: operations["TasksController_getAssignableTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Клонирование дела */
        post: operations["TasksController_cloneTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершение дела */
        post: operations["TasksController_finishTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Восстановление дела */
        post: operations["TasksController_taskRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Полное удаление дела */
        delete: operations["TasksController_completeDeleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перемещение дела в группу */
        post: operations["TasksController_assignTaskToGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/groups/{groupId}/unassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Открепление дела от группы */
        post: operations["TasksController_unassignTaskFromGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Редактирование дела */
        put: operations["TasksController_replaceTask"];
        post?: never;
        /** Удаление дела */
        delete: operations["TasksController_deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/in-box": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создание дела в IN BOX */
        post: operations["TasksInboxController_createTaskIntoInbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/in-box/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перемещение дела в IN BOX */
        post: operations["TasksInboxController_assignTaskToInbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{taskId}/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Редактирование дела в IN BOX */
        put: operations["TasksInboxController_updateTaskInInbox"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDto: {
            /** @example 1 */
            id: number;
            /** @example Крутой ник */
            screenName?: string;
            /** @example test@email.com */
            email: string;
            /** @example /some-url.png */
            avatar?: string;
        };
        MeRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["UserDto"];
        };
        RegisterReqData: {
            /** @example email2@mail.com */
            login: string;
            /** @example 123456 */
            password: string;
        };
        RegisterRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["RegisterReqData"];
        };
        RegisterResData: {
            /** @example jwt token is here */
            token: string;
        };
        RegisterResponse: {
            /** @description Ответ сервера */
            data: components["schemas"]["RegisterResData"];
        };
        RefreshDto: {
            /** @example jwt token is here */
            token: string;
        };
        RefreshResponse: {
            /** @description Ответ сервера */
            data: components["schemas"]["RefreshDto"];
        };
        LogoutResponse: {
            /** @description Ответ сервера */
            data: boolean;
        };
        RequestDto: {
            /** @example email2@mail.com */
            login: string;
            /** @example 123456 */
            password: string;
        };
        LoginRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["RequestDto"];
        };
        ResponseDto: {
            /** @example jwt token is here */
            token: string;
        };
        LoginResponse: {
            /** @description Ответ сервера */
            data: components["schemas"]["ResponseDto"];
        };
        ReferralTokenResData: {
            /** @example Реферальный токен юзера */
            token: string;
        };
        ReferralTokenRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["ReferralTokenResData"];
        };
        RepetitionDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId?: number;
            /** @example 1 */
            exerciseId: number;
            /**
             * @example SKIP
             * @enum {string}
             */
            finishType?: "DONE" | "SKIP" | "TRIED" | "OVER";
            /**
             * @description Желаемое количество повторений
             * @example 1
             */
            targetCount: number;
            /**
             * @description Фактическое количество повторений
             * @example 1
             */
            factCount?: number;
            /**
             * @description Желаемый вec
             * @example 20.5
             */
            targetWeight: string;
            /**
             * @description Фактический вec
             * @example 100.7
             */
            factWeight?: string;
            /**
             * @description Желаемый перерыв, значение в секундах
             * @example 1
             */
            targetBreak: number;
            /**
             * @description Фактический перерыв, значение в секундах
             * @example 1
             */
            factBreak?: number;
        };
        TrainingExerciseWithRepetitionsDto: {
            /** @example 1 */
            id: number;
            /**
             * @example ANAEROBIC
             * @enum {string}
             */
            type: "WORM-UP" | "POST-TRAINING" | "AEROBIC" | "ANAEROBIC";
            /** @example Жим лежа */
            name: string;
            /** @example свести лопатки */
            description?: string;
            /** @example https://youtube.com */
            exampleUrl?: string;
            /** @description Повторения */
            repetitions: components["schemas"]["RepetitionDto"][];
        };
        TrainingWithExercisesDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId: number;
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /** @example 2025-05-24T13:01:02.471Z */
            startDate: string;
            /** @example 2025-06-24T13:01:02.471Z */
            endDate?: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
            inProgress: boolean;
            /** @description Упражнения */
            exercises: components["schemas"]["TrainingExerciseWithRepetitionsDto"][];
        };
        TrainingWithExercisesResponseSingle: {
            /** @description Ответ сервера */
            data: components["schemas"]["TrainingWithExercisesDto"];
        };
        TrainingDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId: number;
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /** @example 2025-05-24T13:01:02.471Z */
            startDate: string;
            /** @example 2025-06-24T13:01:02.471Z */
            endDate?: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
            inProgress: boolean;
        };
        TrainingResponse: {
            /** @description Ответ сервера */
            data: components["schemas"]["TrainingDto"][];
        };
        CreateRepetition: {
            /**
             * @description Желаемое количество повторений
             * @example 1
             */
            targetCount: number;
            /**
             * @description Желаемый вec
             * @example 20.5
             */
            targetWeight: string;
            /**
             * @description Желаемый перерыв, значение в секундах
             * @example 1
             */
            targetBreak: number;
        };
        CreateExerciseWithRepetitionsData: {
            /**
             * @example ANAEROBIC
             * @enum {string}
             */
            type: "WORM-UP" | "POST-TRAINING" | "AEROBIC" | "ANAEROBIC";
            /** @example Жим лежа */
            name: string;
            /** @example свести лопатки */
            description?: string;
            /** @example https://youtube.com */
            exampleUrl?: string;
            /** @description Повторения */
            repetitions: components["schemas"]["CreateRepetition"][];
        };
        CreateTrainingWithExercisesRequestData: {
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            exercises: components["schemas"]["CreateExerciseWithRepetitionsData"][];
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /** @example 2025-05-24T13:01:02.471Z */
            startDate: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
        };
        CreateTrainingWithExercisesRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["CreateTrainingWithExercisesRequestData"];
        };
        CreateTrainingByTemplateRequestData: {
            /** @example 1 */
            templateId: number;
            /** @example 2025-05-24T13:01:02.471Z */
            startDate: string;
        };
        CreateTrainingByTemplateRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["CreateTrainingByTemplateRequestData"][];
        };
        TrainingWithExercisesResponse: {
            /** @description Ответ сервера */
            data: components["schemas"]["TrainingWithExercisesDto"][];
        };
        UpdateRepetition: {
            /**
             * @description Желаемое количество повторений
             * @example 1
             */
            targetCount: number;
            /**
             * @description Желаемый вec
             * @example 20.5
             */
            targetWeight: string;
            /**
             * @description Желаемый перерыв, значение в секундах
             * @example 1
             */
            targetBreak: number;
            /** @example 1 */
            id?: number;
        };
        ExerciseWithRepetitionsRequestData: {
            /**
             * @example ANAEROBIC
             * @enum {string}
             */
            type: "WORM-UP" | "POST-TRAINING" | "AEROBIC" | "ANAEROBIC";
            /** @example Жим лежа */
            name: string;
            /** @example свести лопатки */
            description?: string;
            /** @example https://youtube.com */
            exampleUrl?: string;
            /** @description Повторения */
            repetitions: components["schemas"]["UpdateRepetition"][];
            /** @example 1 */
            id: number;
        };
        UpdateTrainingWithExerciseRequestData: {
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
            exercises: components["schemas"]["ExerciseWithRepetitionsRequestData"][];
        };
        UpdateTrainingWithExerciseRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["UpdateTrainingWithExerciseRequestData"];
        };
        AssignTrainingRequestData: {
            /** @example 1 */
            id: number;
            /** @example 2025-05-24T13:01:02.471Z */
            startDate: string;
        };
        AssignTrainingRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["AssignTrainingRequestData"][];
        };
        FactRepetitionDto: {
            /**
             * @description Фактическое количество повторений
             * @example 1
             */
            factCount: number;
            /**
             * @description Фактический вec
             * @example 100.7
             */
            factWeight: string;
            /**
             * @example SKIP
             * @enum {string}
             */
            finishType: "DONE" | "SKIP" | "TRIED" | "OVER";
        };
        SetRepetitionFactRequest: {
            /** @description Ответ сервера */
            data: components["schemas"]["FactRepetitionDto"];
        };
        SetBreakRequestData: {
            /**
             * @description Фактический перерыв, значение в секундах
             * @example 1
             */
            factBreak: number;
        };
        SetRepetitionBreakRequest: {
            /** @description Ответ сервера */
            data: components["schemas"]["SetBreakRequestData"];
        };
        TrainingTemplateDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId: number;
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
        };
        TrainingTemplateResponse: {
            /** @description Ответ сервера */
            data: components["schemas"]["TrainingTemplateDto"][];
        };
        TrainingTemplateExerciseDto: {
            /** @example 1 */
            id: number;
            /**
             * @example ANAEROBIC
             * @enum {string}
             */
            type: "WORM-UP" | "POST-TRAINING" | "AEROBIC" | "ANAEROBIC";
            /** @example Жим лежа */
            name: string;
            /** @example свести лопатки */
            description?: string;
            /** @example https://youtube.com */
            exampleUrl?: string;
            /** @description Повторения */
            repetitions: components["schemas"]["RepetitionDto"][];
        };
        TrainingTemplateWithExercisesDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId: number;
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
            /** @description Упражнения */
            exercises: components["schemas"]["TrainingTemplateExerciseDto"][];
        };
        TrainingTemplateWithExercisesResponseSingle: {
            /** @description Ответ сервера */
            data: components["schemas"]["TrainingTemplateWithExercisesDto"];
        };
        CreateTrainingTemplateWithExercisesRequestData: {
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
            exercises: components["schemas"]["CreateExerciseWithRepetitionsData"][];
        };
        CreateTrainingTemplateWithExercisesRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["CreateTrainingTemplateWithExercisesRequestData"];
        };
        TemplateExerciseWithRepetitions: {
            /**
             * @example ANAEROBIC
             * @enum {string}
             */
            type: "WORM-UP" | "POST-TRAINING" | "AEROBIC" | "ANAEROBIC";
            /** @example Жим лежа */
            name: string;
            /** @example свести лопатки */
            description?: string;
            /** @example https://youtube.com */
            exampleUrl?: string;
            /** @description Повторения */
            repetitions: components["schemas"]["UpdateRepetition"][];
            /** @example 1 */
            id: number;
        };
        UpdateTrainingTemplateWithExerciseRequestData: {
            /**
             * @example MEDIUM
             * @enum {string}
             */
            type: "LIGHT" | "MEDIUM" | "HARD" | "MIXED";
            /** @example Понедельничная */
            name: string;
            /** @example описание (какие цели на тренировку, на что сделать упор и т.п) */
            description?: string;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            wormUpDuration?: number;
            /**
             * @description измеряется в минутах
             * @example 30
             */
            postTrainingDuration?: number;
            exercises: components["schemas"]["TemplateExerciseWithRepetitions"][];
        };
        UpdateTrainingTemplateWithExerciseRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["UpdateTrainingTemplateWithExerciseRequestData"];
        };
        ExerciseWithRepetitionsDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            userId?: number;
            /**
             * @example ANAEROBIC
             * @enum {string}
             */
            type: "WORM-UP" | "POST-TRAINING" | "AEROBIC" | "ANAEROBIC";
            /** @example Жим лежа */
            name: string;
            /** @example свести лопатки */
            description?: string;
            /** @example https://youtube.com */
            exampleUrl?: string;
            /** @example 1 */
            trainingId?: number;
            /** @example 1 */
            templateId?: number;
            /** @description Повторения */
            repetitions: components["schemas"]["RepetitionDto"][];
        };
        ExerciseWithRepetitionsResponse: {
            /** @description Ответ сервера */
            data: components["schemas"]["ExerciseWithRepetitionsDto"][];
        };
        CreateExerciseWithRepetitionsRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["CreateExerciseWithRepetitionsData"];
        };
        ExerciseWithRepetitionsResponseSingle: {
            /** @description Ответ сервера */
            data: components["schemas"]["ExerciseWithRepetitionsDto"];
        };
        UpdateExerciseWithRepetitionsData: {
            /**
             * @example ANAEROBIC
             * @enum {string}
             */
            type: "WORM-UP" | "POST-TRAINING" | "AEROBIC" | "ANAEROBIC";
            /** @example Жим лежа */
            name: string;
            /** @example свести лопатки */
            description?: string;
            /** @example https://youtube.com */
            exampleUrl?: string;
            /** @description Повторения */
            repetitions: components["schemas"]["UpdateRepetition"][];
        };
        UpdateExerciseWithRepetitionsRequest: {
            /** @description Данные для запроса */
            data: components["schemas"]["UpdateExerciseWithRepetitionsData"];
        };
        TaskRecurrencyDto: {
            /**
             * @description Частота
             * @example 3
             * @enum {number}
             */
            frequency: 0 | 1 | 2 | 3 | 4 | 5 | 6;
            /**
             * @description Дни недели
             * @example [
             *       0,
             *       3
             *     ]
             */
            weekdays?: (0 | 1 | 2 | 3 | 4 | 5 | 6)[];
            /**
             * @description День начала повторения. Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            startDate: string;
            /**
             * @description День окончания повторения. Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            untilDate?: string;
            /**
             * @description Дни месяца
             * @example [
             *       1,
             *       15
             *     ]
             */
            monthdays?: string[];
            /**
             * @description Месяцы года
             * @example [
             *       1,
             *       4
             *     ]
             */
            yearmonths?: string[];
            /**
             * @description Интервал повторения (каждые n дней/недель/месяцев/лет)
             * @example 3
             */
            interval?: number;
        };
        TaskDto: {
            /**
             * @description t:4 - это реальное дело, v:4:2026.02.02 - виртуальная
             * @example t:4
             */
            id: string;
            /** @example Имя дела */
            name: string;
            /** @example Описание */
            description?: string;
            /** @example 1 */
            userId: number;
            /** @example 1 */
            groupId?: number;
            /**
             * @description От 1 до 4
             * @example 2
             */
            priority: number;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            endDate?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            startDate?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            deadline?: string;
            /**
             * @description От 0 до 100
             * @example 100
             */
            weight: number;
            /** @example Описание причины не выполнения дела */
            cancelReason?: string;
            /**
             * @description Статус дела
             * @example NOT_STARTED
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "OVERDUE" | "CANCELLED" | "ARCHIVED" | "DELETED";
            /** @description Паттерн повторения дела */
            recurrence?: components["schemas"]["TaskRecurrencyDto"];
        };
        GetInBoxRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["TaskDto"][];
        };
        GroupDto: {
            /** @example 1 */
            id: number;
            /** @example Группа дел */
            name: string;
            /** @example Описание */
            description?: string;
            /** @example 1 */
            userId: number;
            /**
             * @description От 0 до 100
             * @example 40
             */
            progress: number;
            /**
             * @description Статус группы
             * @example NOT_STARTED
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "DONE";
            /** @description Список дел */
            tasks: components["schemas"]["TaskDto"][];
        };
        CursorPaginationResDto: {
            /**
             * @description Курсор пагинации
             * @example eyJsYXN0SWQiOjEyMywic29ydCI6ImNyZWF0ZWRfYXQiLCJvcmRlc
             */
            cursor?: string;
        };
        GetUserGroupsResData: {
            /** @description Ответ сервера */
            items: components["schemas"]["GroupDto"][];
            /** @description Метаинформация */
            meta: components["schemas"]["CursorPaginationResDto"];
        };
        GetUserGroupsRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["GetUserGroupsResData"];
        };
        GroupDetailedDto: {
            /** @example 1 */
            id: number;
            /** @example Группа дел */
            name: string;
            /** @example Описание */
            description?: string;
            /** @example 1 */
            userId: number;
            /**
             * @description От 0 до 100
             * @example 40
             */
            progress: number;
            /**
             * @description Статус группы
             * @example NOT_STARTED
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "DONE";
            /** @description Список дел */
            tasks: components["schemas"]["TaskDto"][];
        };
        GetDetailedGroupsRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["GroupDetailedDto"];
        };
        GroupInfoDto: {
            /** @example 1 */
            id: number;
            /** @example Группа дел */
            name: string;
        };
        GetAssignableGroupsRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["GroupInfoDto"][];
        };
        CreateGroupReqData: {
            /** @example Название группы */
            name: string;
            /** @example Описание */
            description?: string;
        };
        CreateGroupReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["CreateGroupReqData"];
        };
        CreateGroupResData: {
            /** @example 1 */
            id: number;
            /** @example Группа дел */
            name: string;
            /** @example Описание */
            description?: string;
            /** @example 1 */
            userId: number;
            /**
             * @description От 0 до 100
             * @example 40
             */
            progress: number;
            /**
             * @description Статус группы
             * @example NOT_STARTED
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "DONE";
        };
        CreateGroupRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["CreateGroupResData"];
        };
        ReplaceGroupTask: {
            /** @example 1 */
            id: string;
            /** @example Имя дела */
            name: string;
            /** @example Описание */
            description?: string;
            /**
             * @description От 1 до 4
             * @example 2
             */
            priority?: number;
            /**
             * @description От 0 до 100
             * @example 100
             */
            weight: number;
            /** @description Паттерн повторения дела */
            recurrence?: components["schemas"]["TaskRecurrencyDto"];
        };
        ReplaceGroupReqData: {
            /** @example Название группы */
            name: string;
            /** @example Описание */
            description?: string;
            /** @description Список дел */
            tasks: components["schemas"]["ReplaceGroupTask"][];
        };
        ReplaceGroupReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["ReplaceGroupReqData"];
        };
        ReplaceGroupRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["GroupDto"];
        };
        DeleteGroupRes: {
            /** @description Ответ сервера */
            data: boolean;
        };
        GetTasksSortDto: {
            /**
             * @description Сортировка по приоритету
             * @example ASC
             * @enum {string}
             */
            priority?: "ASC" | "DESC";
            /**
             * @description Сортировка по дедлайну
             * @example ASC
             * @enum {string}
             */
            deadline?: "ASC" | "DESC";
            /**
             * @description Сортировка по дате старта
             * @example ASC
             * @enum {string}
             */
            startDate?: "ASC" | "DESC";
        };
        GetTasksFilterDto: {
            /**
             * @description Приоритет фильтрации
             * @example 2
             */
            priority?: number;
            /**
             * @description IDs групп
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            group?: number[];
            /**
             * @description Статусы
             * @example [
             *       "NOT_STARTED"
             *     ]
             */
            status?: ("NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "OVERDUE" | "CANCELLED")[];
            /**
             * @description Начало диапазона (ISO 8601). Должно приходить вместе с filter.to
             * @example 2026-01-01T00:00:00.000Z
             */
            from?: string;
            /**
             * @description Конец диапазона (ISO 8601). Должно приходить вместе с filter.from
             * @example 2026-02-01T00:00:00.000Z
             */
            to?: string;
        };
        PaginationResDto: {
            /**
             * @description Наличие следующей страницы
             * @example true
             */
            nextPage?: boolean;
        };
        GetTasksResData: {
            /** @description Ответ сервера */
            items: components["schemas"]["TaskDto"][];
            /** @description Метаинформация */
            meta: components["schemas"]["PaginationResDto"];
        };
        GetTasksRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["GetTasksResData"];
        };
        GetDiaryTasksFilterDto: {
            /**
             * @description Без времени, только день
             * @example 2026-01-01
             */
            from: string;
            /**
             * @description Без времени, только день
             * @example 2026-01-01
             */
            to: string;
            /**
             * @description IDs групп
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            group?: number[];
        };
        GetDeletedTasksResData: {
            /** @description Ответ сервера */
            items: components["schemas"]["TaskDto"][];
            /** @description Метаинформация */
            meta: components["schemas"]["PaginationResDto"];
        };
        GetDeletedTasksRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["GetDeletedTasksResData"];
        };
        GetArchivedTasksResData: {
            /** @description Ответ сервера */
            items: components["schemas"]["TaskDto"][];
            /** @description Метаинформация */
            meta: components["schemas"]["PaginationResDto"];
        };
        GetArchivedTasksRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["GetArchivedTasksResData"];
        };
        GetAssignableTasksRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["TaskDto"][];
        };
        CreateTaskReqData: {
            /** @example 1 */
            groupId?: number;
            /** @example Имя дела */
            name: string;
            /**
             * @description От 1 до 4
             * @example 2
             */
            priority?: number;
            /**
             * @description От 0 до 100
             * @example 100
             */
            weight?: number;
            /** @example Описание дела */
            description?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            startDate?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            deadline?: string;
            /** @description Паттерн повторения дела */
            recurrence?: components["schemas"]["TaskRecurrencyDto"];
        };
        CreateTaskReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["CreateTaskReqData"];
        };
        CreateTaskRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["TaskDto"];
        };
        CloneTaskReqData: {
            /** @example 1 */
            groupId?: number;
        };
        CloneTaskReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["CloneTaskReqData"];
        };
        CloneTaskRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["TaskDto"];
        };
        FinishTaskRes: {
            /** @description Ответ сервера */
            data: boolean;
        };
        TaskRecoveryReqData: {
            /** @example 1 */
            groupId?: number;
        };
        TaskRecoveryReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["TaskRecoveryReqData"];
        };
        TaskRecoveryResData: {
            /** @example 123 */
            id: number;
        };
        TaskRecoveryRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["TaskRecoveryResData"];
        };
        CompleteDeleteTaskResData: {
            /** @example 123 */
            id: number;
        };
        CompleteDeleteTaskRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["CompleteDeleteTaskResData"];
        };
        AssignTaskToGroupResData: {
            /** @example true */
            success: boolean;
        };
        AssignTaskToGroupRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["AssignTaskToGroupResData"];
        };
        UnassignTaskFromGroupResData: {
            /** @example true */
            success: boolean;
        };
        UnassignTaskFromGroupRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["UnassignTaskFromGroupResData"];
        };
        ReplaceTaskReqData: {
            /** @example Имя дела */
            name: string;
            /** @example Описание дела */
            description?: string;
            /**
             * @description От 1 до 4
             * @example 2
             */
            priority: number;
            /**
             * @description От 0 до 100
             * @example 100
             */
            weight: number;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            startDate?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            deadline?: string;
            /** @description Паттерн повторения дела */
            recurrence?: components["schemas"]["TaskRecurrencyDto"];
        };
        ReplaceTaskReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["ReplaceTaskReqData"];
        };
        ReplaceTaskRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["TaskDto"];
        };
        CreateTaskInINBOXReqData: {
            /** @example Имя дела */
            name: string;
            /**
             * @description От 1 до 4
             * @example 2
             */
            priority?: number;
            /** @example Описание дела */
            description?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            startDate?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            deadline?: string;
        };
        CreateTaskInINBOXReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["CreateTaskInINBOXReqData"];
        };
        AssignTaskToInboxResData: {
            /** @example true */
            success: boolean;
        };
        AssignTaskToInboxRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["AssignTaskToInboxResData"];
        };
        UpdateInboxTaskReqData: {
            /** @example Имя дела */
            name: string;
            /** @example Описание дела */
            description?: string;
            /**
             * @description От 1 до 4
             * @example 2
             */
            priority: number;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            startDate?: string;
            /**
             * @description Абсолютная точка во времени без локализации и без таймзоны. Формат: 2026-03-11T21:04
             * @example 2026-03-11T21:04
             */
            deadline?: string;
        };
        UpdateInboxTaskReq: {
            /** @description Запрос сервера */
            data: components["schemas"]["UpdateInboxTaskReqData"];
        };
        UpdateInboxTaskRes: {
            /** @description Ответ сервера */
            data: components["schemas"]["TaskDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeRes"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Пользователь успешно зарегистрирован */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Токен успешно продлен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выход совершен успешно */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Вход совершен успешно */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    AuthController_generateReferralToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralTokenRes"];
                };
            };
        };
    };
    AuthController_validateReferralToken: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralTokenRes"];
                };
            };
        };
    };
    TrainingsController_getActiveTraining: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingWithExercisesResponseSingle"];
                };
            };
        };
    };
    TrainingsController_getTrainings: {
        parameters: {
            query?: {
                /** @description ISO String */
                from?: string;
                /** @description ISO String */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingResponse"];
                };
            };
        };
    };
    TrainingsController_createTraining: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrainingWithExercisesRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingWithExercisesResponseSingle"];
                };
            };
        };
    };
    TrainingsController_getOneTrainingsWithExercises: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingWithExercisesResponseSingle"];
                };
            };
        };
    };
    TrainingsController_putTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrainingWithExerciseRequest"];
            };
        };
        responses: {
            /** @description Тренировка обновлена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingWithExercisesResponseSingle"];
                };
            };
        };
    };
    TrainingsController_deleteTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тренировка удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainingsController_createTrainingByTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrainingByTemplateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingWithExercisesResponse"];
                };
            };
        };
    };
    TrainingsController_assignTrainings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignTrainingRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainingsController_stratTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainingsController_finishTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainingsController_setFact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repetitionId: number;
                trainingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRepetitionFactRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainingsController_setBrakFact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repetitionId: number;
                trainingId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRepetitionBreakRequest"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrainingTemplatesController_getTrainingTemplates: {
        parameters: {
            query?: {
                my?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingTemplateResponse"];
                };
            };
        };
    };
    TrainingTemplatesController_createTraining: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrainingTemplateWithExercisesRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingTemplateWithExercisesResponseSingle"];
                };
            };
        };
    };
    TrainingTemplatesController_getOneTrainingsWithExercises: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingTemplateWithExercisesResponseSingle"];
                };
            };
        };
    };
    TrainingTemplatesController_putTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrainingTemplateWithExerciseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingTemplateWithExercisesResponseSingle"];
                };
            };
        };
    };
    TrainingTemplatesController_deleteTraining: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тренировка удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExercisesController_getExercises: {
        parameters: {
            query?: {
                my?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseWithRepetitionsResponse"];
                };
            };
        };
    };
    ExercisesController_getOneExerciseWithRepetitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseWithRepetitionsResponse"];
                };
            };
        };
    };
    ExercisesController_updateExerciseWithRepetitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExerciseWithRepetitionsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseWithRepetitionsResponseSingle"];
                };
            };
        };
    };
    ExercisesController_createExerciseWithRepetitions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExerciseWithRepetitionsRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseWithRepetitionsResponseSingle"];
                };
            };
        };
    };
    ExercisesController_deleteExerciseTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exerciseId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GroupsController_getInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInBoxRes"];
                };
            };
        };
    };
    GroupsController_getUserGroups: {
        parameters: {
            query: {
                /** @description Курсор пагинации */
                cursor?: string;
                /** @description Шаг пагинации */
                limit: number;
                /** @description Очень важная группа */
                search?: string;
                /** @description Сортировка по дефолту id */
                sort?: string[];
                /** @description Фильтрация */
                filter?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserGroupsRes"];
                };
            };
        };
    };
    GroupsController_createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupReq"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGroupRes"];
                };
            };
        };
    };
    GroupsController_getDetailedGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDetailedGroupsRes"];
                };
            };
        };
    };
    GroupsController_getAssignableGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAssignableGroupsRes"];
                };
            };
        };
    };
    GroupsController_replaceGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceGroupReq"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaceGroupRes"];
                };
            };
        };
    };
    GroupsController_deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteGroupRes"];
                };
            };
        };
    };
    TasksController_getTasks: {
        parameters: {
            query: {
                /** @description Какая страниц */
                page: number;
                /** @description Элементов в странице */
                perPage: number;
                /** @description Поиск по имени */
                search?: string;
                /** @description Параметры сортировки */
                sort?: components["schemas"]["GetTasksSortDto"];
                /** @description Параметры фильтрации */
                filter?: components["schemas"]["GetTasksFilterDto"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTasksRes"];
                };
            };
        };
    };
    TasksController_createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskReq"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskRes"];
                };
            };
        };
    };
    TasksController_getDiaryTasks: {
        parameters: {
            query?: {
                /** @description Параметры фильтрации */
                filter?: components["schemas"]["GetDiaryTasksFilterDto"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTasksRes"];
                };
            };
        };
    };
    TasksController_getDeletedTasks: {
        parameters: {
            query: {
                /** @description Какая страниц */
                page: number;
                /** @description Элементов в странице */
                perPage: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDeletedTasksRes"];
                };
            };
        };
    };
    TasksController_getArchivedTasks: {
        parameters: {
            query: {
                /** @description Какая страниц */
                page: number;
                /** @description Элементов в странице */
                perPage: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetArchivedTasksRes"];
                };
            };
        };
    };
    TasksController_getAssignableTasks: {
        parameters: {
            query: {
                /** @description Очень важное дело */
                search: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAssignableTasksRes"];
                };
            };
        };
    };
    TasksController_cloneTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CloneTaskReq"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloneTaskRes"];
                };
            };
        };
    };
    TasksController_finishTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinishTaskRes"];
                };
            };
        };
    };
    TasksController_taskRecovery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRecoveryReq"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRecoveryRes"];
                };
            };
        };
    };
    TasksController_completeDeleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteDeleteTaskRes"];
                };
            };
        };
    };
    TasksController_assignTaskToGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignTaskToGroupRes"];
                };
            };
        };
    };
    TasksController_unassignTaskFromGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnassignTaskFromGroupRes"];
                };
            };
        };
    };
    TasksController_replaceTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceTaskReq"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplaceTaskRes"];
                };
            };
        };
    };
    TasksController_deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksInboxController_createTaskIntoInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskInINBOXReq"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskRes"];
                };
            };
        };
    };
    TasksInboxController_assignTaskToInbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignTaskToInboxRes"];
                };
            };
        };
    };
    TasksInboxController_updateTaskInInbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInboxTaskReq"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateInboxTaskRes"];
                };
            };
        };
    };
}
