enum GoalStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  CANCELED = 'CANCELED',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
}

export { GoalStatus };
