services:
  db:
    image: postgres:15
    env_file:
      - .env.development
    container_name: tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - trackerdata:/var/lib/postgresql/data

volumes:
  trackerdata:
