/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Exercises {
  created_at: Generated<Timestamp>;
  description: string | null;
  example_url: string | null;
  id: Generated<number>;
  name: string;
  position: Generated<number>;
  training_id: number | null;
  training_template_id: number | null;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: number | null;
}

export interface ExerciseTypes {
  value: string;
}

export interface Repetitions {
  created_at: Generated<Timestamp>;
  description: string | null;
  exercise_id: number;
  fact_break: number | null;
  fact_count: number | null;
  fact_weight: Numeric | null;
  finish_type: string | null;
  id: Generated<number>;
  position: Generated<number>;
  target_break: number;
  target_count: number;
  target_weight: Numeric;
  updated_at: Generated<Timestamp>;
  user_id: number | null;
}

export interface RepetitionsTypes {
  value: string;
}

export interface Trainings {
  created_at: Generated<Timestamp>;
  description: string | null;
  end_date: Timestamp | null;
  id: Generated<number>;
  in_progress: Generated<boolean>;
  name: string;
  post_training_duration: number | null;
  start_date: Generated<Timestamp>;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: number;
  worm_up_duration: number | null;
}

export interface TrainingsTemplates {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  post_training_duration: number | null;
  type: string;
  updated_at: Generated<Timestamp>;
  user_id: number | null;
  worm_up_duration: number | null;
}

export interface TrainingsTypes {
  value: string;
}

export interface DB {
  exercise_types: ExerciseTypes;
  exercises: Exercises;
  repetitions: Repetitions;
  repetitions_types: RepetitionsTypes;
  trainings: Trainings;
  trainings_templates: TrainingsTemplates;
  trainings_types: TrainingsTypes;
}
