const SENSITIVE_LOG_PATHS = [
  'token',
  'login',
  'password',
  'data.token',
  'data.data.token',
  'data.login',
  'data.data.login',
  'data.password',
  'data.data.password',
  'data.refreshToken',
  'data.sessionToken',
  'data.session',
  'body.token',
  'body.login',
  'body.password',
  'payload.token',
  'payload.login',
  'payload.password',
  'req.query.token',
  'req.query.accessToken',
  'req.query.refreshToken',
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers.set-cookie',
  "req.headers['x-api-key']",
  'req.body.token',
  'req.body.login',
  'req.body.password',
  'req.body.data.token',
  'req.body.data.login',
  'req.body.data.password',
  'err.stack',
  'error.stack',
] as const;

export { SENSITIVE_LOG_PATHS };
